### ISSUE TITLE
add `.hpp` file extension

### ISSUE THREAD

**Issue by lrvideckis** [pin3da/notebook-generator#24]
https://github.com/pin3da/notebook-generator/blob/master/notebookgen.js#L9

- My lib has only .hpp files

**Comment by pin3da** [comment]
Hey! I just added it to the list, I hope it helps :)

Feel free to send a PR if you see any other fix/improvement. 

Thanks.

**Comment by lrvideckis** [comment]
Thanks!

**Comment by lrvideckis** [comment]
@pin3da Can you update the npm package too?

**Comment by lrvideckis** [comment]
Thanks again for adding! My notebook now uses your repo

**Comment by pin3da** [comment]
Nice! I just managed to update the npm package, so this should work for new installations too.
