### ISSUE TITLE
switch to monospace width font?

### ISSUE THREAD

**Issue by lrvideckis** [pin3da/notebook-generator#32]

**Comment by lrvideckis** [comment]
![2023-07-18-114152_252x320_scrot](https://github.com/pin3da/notebook-generator/assets/33103480/966c1f40-2fc5-4b24-a481-542c71def9dd)
![2023-07-18-114203_308x384_scrot](https://github.com/pin3da/notebook-generator/assets/33103480/15bd496c-da86-42ba-b8b2-ec1495b85d2c)

**Comment by pin3da** [comment]
Thanks! This seems like a sensible proposal to me :)

Could you send a PR with the changes? I'd be happy to review and merge.
